[Rainmeter]
Update=25
AccurateText=1
BackgroundMode=2
SolidColor=0,0,0,1

[Variables]
FontColor=FFFFFF
FontSize=14
ImageSize=125
Padding=10

[MeasureWebNowPlaying]
Measure=Plugin
Plugin=WebNowPlaying
PlayerName=Chrome

[MeasurePlayerName]
Measure=Plugin
Plugin=WebNowPlaying
PlayerName=Chrome
PlayerType=PLAYER

[MeasureTitle]
Measure=Plugin
Plugin=WebNowPlaying
PlayerName=Chrome
PlayerType=TITLE
UpdateDivider=-1

[MeasureArtist]
Measure=Plugin
Plugin=WebNowPlaying
PlayerName=Chrome
PlayerType=ARTIST

[MeasureCover]
Measure=Plugin
Plugin=WebNowPlaying
PlayerName=Chrome
PlayerType=COVER

[MeasureState]
Measure=Plugin
Plugin=WebNowPlaying
PlayerName=Chrome
PlayerType=STATE

[MeasureProgress]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=PROGRESS

[MeasureWinColor]
Measure=Plugin
Plugin=SysColor
ColorType=Accent


;-----------------------------------------------------

[Box]
Meter=Shape
X=10
Y=10
Shape=Rectangle 0,0,400,170,12 | Fill Color 255,255,255,30 | StrokeWidth 0
Group=PlayerGroup

[PlayerNameText]
Meter=String
X=390
Y=25
FontColor=FFFFFF96 
FontSize=10
StringAlign=Right
DynamicVariables=1
Text=""
AntiAlias=1
Group=PlayerGroup

[PlayerNameTextCondition]
Measure=Calc
Formula=MeasureState
IfCondition=(MeasureState=0)
IfTrueAction=[!SetOption PlayerNameText Text "MyMusicPlayer"][!UpdateMeter PlayerNameText][!Redraw]
IfFalseAction=[!SetOption PlayerNameText Text "[MeasurePlayerName]"][!UpdateMeter PlayerNameText][!Redraw]
DynamicVariables=1
AntiAlias=1
Group=PlayerGroup

[TitleText]
Meter=String
MeasureName=MeasureTitle
X=165
Y=50
W=230
H=30 
FontSize=#FontSize#
FontColor=#FontColor#
FontWeight=700
AntiAlias=1
Text="%1"
StringAlign=Left
ClipString=1
DynamicVariables=1
Group=PlayerGroup

[ArtistText]
Meter=String
MeasureName=MeasureArtist
X=165
Y=80
W=230
FontSize=#FontSize#
FontWeight=400
FontColor=[MeasureWinColor]
StringAlign=Left
AntiAlias=1
Text="%1"
StringAlign=Left
ClipString=1
DynamicVariables=1
Group=PlayerGroup

[CoverShape]
Meter=Shape
X=25
Y=25
Shape=Rectangle 0,0,#ImageSize#,#ImageSize#,12 | Fill Color 0,0,0 | StrokeWidth 0
Group=PlayerGroup

[AlbumCover]
Meter=Image
MeasureName=MeasureCover
X=0
Y=0
W=#ImageSize#
H=#ImageSize#
Container=CoverShape
PreserveAspectRatio=1
ImageName=#@#null.png
LeftMouseUpAction=[!CommandMeasure MeasureWebNowPlaying "PlayPause"]
DynamicVariables=1
Group=PlayerGroup

[ProgressBar]
Meter=Bar
MeasureName=MeasureProgress
X=25
Y=160
W=370
H=2
BarColor=[MeasureWinColor]
SolidColor=255,255,255,30
BarOrientation=Horizontal
DynamicVariables=1
Group=PlayerGroup

[PlayIcon]
Meter=Image
X=265
Y=122
W=25
H=25
ImageName=#@#play.png
LeftMouseUpAction=[!CommandMeasure MeasureWebNowPlaying "PlayPause"][!UpdateMeasure MeasureState][!UpdateMeter PlayIcon][!Redraw]
DynamicVariables=1
Group=PlayerGroup

[PlayPauseLogic]
Measure=Calc
Formula=MeasureState
IfCondition=(MeasureState=1)
IfTrueAction=[!SetOption PlayIcon ImageName "#@#pause.png"][!UpdateMeter PlayIcon][!Redraw]
IfFalseAction=[!SetOption PlayIcon ImageName "#@#play.png"][!UpdateMeter PlayIcon][!Redraw]
DynamicVariables=1
Group=PlayerGroup

[PrevIcon]
Meter=Image
X=230
Y=125
W=20
H=20
ImageName=#@#prev.png
LeftMouseUpAction=[!CommandMeasure MeasureWebNowPlaying "Previous"][!UpdateMeasure MeasureState][!UpdateMeter PlayIcon][!Redraw]
DynamicVariables=1
Group=PlayerGroup

[NextIcon]
Meter=Image
X=305
Y=125
W=20
H=20
ImageName=#@#next.png
LeftMouseUpAction=[!CommandMeasure MeasureWebNowPlaying "Next"][!UpdateMeasure MeasureState][!UpdateMeter PlayIcon][!Redraw]
DynamicVariables=1
Group=PlayerGroup

[PlayPause]
Meter=Image
X=150
Y=250
W=30
H=30
LeftMouseUpAction=[!CommandMeasure MeasureWebNowPlaying "PlayPause"]
DynamicVariables=1
Group=PlayerGroup


[HideALL]
Measure=Calc
Formula=MeasureState
IfCondition=MeasureState=0
IfTrueAction=[!HideMeterGroup "PlayerGroup"][!UpdateMeter *][!Redraw]
IfFalseAction=[!ShowMeterGroup "PlayerGroup"][!UpdateMeter *][!Redraw]

;Copyright © 2026 by Jojo